spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security_directory
    username: springsecurity
    password: springsecurity
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
app:
  jwt:
   sign-in-key: o3pOR29s1IWMQazKMHFjPWap4oKKyAmmo3pOR29s1IWMQazKMHFjPWap4oKKyAmmo3pOR29s1IWMQazKMHFjPWap4oKKyAmm
   exp-time: 1440000


  